export const paths = {
  root: '/',
  adminRoot: '/admin',
  login: 'login',
  counter: 'counter',
  signup: 'signup',
  forgotPassword: 'forgotPassword',
  requestProfile: 'request-profile',
  userProfile: 'user-profile',
  dashboard: 'dashboard',
  assets: 'assets',
  issues: 'issues-raised',
  employeeProfile:'employee-Profile',
  newTicket: 'raise-ticket',
  requestAsset: 'request-asset',
  logout: 'logout',
  addNewAsset:'add-new-asset',
  allAssets:'assets',
  raisedTickets:'tickets',
  warranty:'ticketsWarranty',
  AssetAllocated:'employee-asset-allocation',
  AssetDetail:'asset-detail',
};
